type Query {
  forms: [Form!]!
  form(id: Int!): Form
  user(id: Int): User
}

type Mutation {
  login(email: String!): serverAnswer
  register(name: String!, email: String!): serverAnswer
  createForm(title: String!, questions: String!): Form!
  formSubmit(formId: Int!, answers: String!): serverAnswer
}

type Form {
  id: Int!
  title: String!
  questions: [Question!]!
  submissions: [FormSubmission!]!
  dateCreated: String!
  author: User
}

interface Question {
  title: String!
  number: Int!
}

type ChoisesQuestion implements Question {
  title: String!
  variants: [Variant!]!
  type: ChoiseType!
  number: Int!
}

type Variant {
  text: String!
}

type InputQuestion implements Question {
  title: String!
  number: Int!
}

type FormSubmission {
  id: Int!
  answers: [Answer!]!
  date: String!
}

interface Answer {
  type: AnswerType!
}

type InputAnswer implements Answer {
  type: AnswerType!
  userInput: String
}

type ChoiseAnswer implements Answer {
  type: AnswerType!
  userChoise: Int!
}

enum ChoiseType {
  SELECT
  CHECK
  CHOOSE
}

enum AnswerType {
  INPUT
  CHOISE
}

type User {
  name: String!
  email: String!
  id: Int!
  forms: [Form!]
}

type serverAnswer {
  success: Boolean!
}
